"""Add brand_asset_ids to scheduled_posts

Revision ID: 22b468c3b71d
Revises: 711d49789160
Create Date: 2026-01-25 22:15:34.695842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b468c3b71d'
down_revision: Union[str, None] = '711d49789160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_posts', sa.Column('brand_asset_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_posts', 'brand_asset_ids')
    # ### end Alembic commands ###
