"""add_brand_colors_to_tenants

Revision ID: 37a5d49ce78f
Revises: 22b468c3b71d
Create Date: 2026-02-03 16:13:56.307016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a5d49ce78f'
down_revision: Union[str, None] = '22b468c3b71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('brand_colors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'brand_colors')
    # ### end Alembic commands ###
