"""Add is_logo flag to brand_assets

Revision ID: 711d49789160
Revises: c1d2e3f4g5h6
Create Date: 2026-01-25 22:08:08.352780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '711d49789160'
down_revision: Union[str, None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_tokens_token', table_name='email_tokens')
    op.drop_index('ix_email_tokens_user_id', table_name='email_tokens')
    op.drop_table('email_tokens')
    op.add_column('brand_assets', sa.Column('is_logo', sa.Boolean(), nullable=True))
    op.alter_column('scheduled_posts', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_posts', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('brand_assets', 'is_logo')
    op.create_table('email_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_type', postgresql.ENUM('verify_email', 'reset_password', name='emailtokentype'), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='email_tokens_pkey')
    )
    op.create_index('ix_email_tokens_user_id', 'email_tokens', ['user_id'], unique=False)
    op.create_index('ix_email_tokens_token', 'email_tokens', ['token'], unique=False)
    # ### end Alembic commands ###
