"""add_performance_max_fields_to_campaign

Revision ID: d04938498084
Revises: e2a7c91d8f3b
Create Date: 2025-12-14 18:51:15.350333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04938498084'
down_revision: Union[str, None] = 'e2a7c91d8f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('final_url', sa.String(length=500), nullable=True))
    op.add_column('campaigns', sa.Column('business_name', sa.String(length=255), nullable=True))
    op.add_column('campaigns', sa.Column('call_to_action', sa.String(length=50), nullable=True))
    op.add_column('campaigns', sa.Column('headlines', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('descriptions', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('ad_strength', sa.String(length=20), nullable=True))
    op.drop_column('campaigns', 'creative_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('creative_preference', sa.VARCHAR(length=20), server_default=sa.text("'both'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('campaigns', 'ad_strength')
    op.drop_column('campaigns', 'descriptions')
    op.drop_column('campaigns', 'headlines')
    op.drop_column('campaigns', 'call_to_action')
    op.drop_column('campaigns', 'business_name')
    op.drop_column('campaigns', 'final_url')
    # ### end Alembic commands ###
