"""add_creative_preference_to_campaigns

Revision ID: f3d38c248ae5
Revises: d04938498084
Create Date: 2025-12-15 01:15:53.015143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d38c248ae5'
down_revision: Union[str, None] = 'd04938498084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('creative_preference', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'creative_preference')
    # ### end Alembic commands ###
